"""fornecedor

Revision ID: 62dfb73d10e6
Revises: 
Create Date: 2024-09-11 15:25:49.341672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dfb73d10e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_fornecedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
